### ISSUE TITLE
【投稿】面向资源编程：更好的数字所有权模型

### ISSUE THREAD

**Issue by zhenfeng-zhu** [WeLightProject/Web3-dApp-Camp#101]
中文：https://www.yuque.com/0xfenix/launn4/kdrk0o
英文：https://medium.com/dapperlabs/resource-oriented-programming-bee4d69c8f8e

**Comment by zhenfeng-zhu** [comment]
[面向资源编程：更好的数字所有权模型.md](https://github.com/WeLightProject/Web3-dApp-Camp/files/9139580/default.md)

**Comment by leeduckgo** [comment]
Good Good.
Money: `400R`
