### ISSUE TITLE
【内容产出挑战】Move 语言教程补全之 Counter 源码分析

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Web3-dApp-Camp#104]
Money: `400R`

对第一个合约案例的源码做下分析。

`TODO` in 
> https://github.com/WeLightProject/Web3-dApp-Camp/blob/main/move-dapp/CryptoXiuXian%20in%20Move%20Lang.md#13-contract-framework

**Comment by hqwangningbo** [comment]
淦 ！

**Comment by hqwangningbo** [comment]
1
