### ISSUE TITLE
【内容产出计划】【Move 指南】通过 js sdk 操作资源

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Web3-dApp-Camp#111]
Money: `800R`

See `todo` in:

https://github.com/WeLightProject/Web3-dApp-Camp/blob/main/move-dapp/CryptoXiuXian%20in%20Move%20Lang.md#144-%E6%93%8D%E4%BD%9C%E8%B5%84%E6%BA%90

**Comment by dajuguan** [comment]
claim
