### ISSUE TITLE
Move极速入门文档补充

### ISSUE THREAD

**Issue by dajuguan** [WeLightProject/Web3-dApp-Camp#115]
- Money: `400R`
Claim

**Comment by leeduckgo** [comment]
- https://github.com/WeLightProject/Web3-dApp-Camp/blob/main/move-dapp/CryptoXiuXian%20in%20Move%20Lang.md#133-%E6%8E%A7%E5%88%B6%E5%8F%B0%E8%B0%83%E7%94%A8
- https://github.com/WeLightProject/Web3-dApp-Camp/blob/main/move-dapp/CryptoXiuXian%20in%20Move%20Lang.md#131-%E7%BC%96%E8%AF%91
