### ISSUE TITLE
Impl the verify_eth_sig function

### ISSUE THREAD

**Issue by tiankonglan** [WeLightProject/Web3-dApp-Camp#126]
https://github.com/WeLightProject/Web3-dApp-Camp/blob/main/move-dapp/eth-sig-verifier/sources/EthSigVerifier.move
      // TODO: impl:
      // 0x01) recover addr from signature
      // --- ecrecover(hash: vector<u8>, signature: vector<u8>)      // cond2 = (addr1 == addr2)
      // 0x02 addr == ecrecover

**Comment by tiankonglan** [comment]
I have impl the function and add the unit test;   PR: https://github.com/WeLightProject/Web3-dApp-Camp/pull/127

**Comment by leeduckgo** [comment]
Money: `50 xUSDT`
