### ISSUE TITLE
【悬赏教程】一篇 loogies-svg-nft 教程

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Web3-dApp-Camp#37]
悬赏价格：`¥500`

- 部署完全教程，包含关键源码分析（`App.jsx`）

   （该源码需和master主分支的更新合并）

> https://github.com/scaffold-eth/scaffold-eth/tree/loogies-svg-nft

拆分金额：`¥300`

- 智能合约源码分析

拆分金额：`¥200`

**Comment by qiwihui** [comment]
请问大家都可以投稿吗？我想投稿

**Comment by leeduckgo** [comment]
> 请问大家都可以投稿吗？我想投稿

可以哦，加我微信：197626581

**Comment by qiwihui** [comment]
> > 请问大家都可以投稿吗？我想投稿
> 
> 
> 
> 可以哦，加我微信：197626581

已加

**Comment by leeduckgo** [comment]
Done. See in:
> https://mp.weixin.qq.com/s/WvTFk3E6FjfHtXfp2uHkrw

**Comment by leeduckgo** [comment]
recorded in `https://github.com/WeLightProject/tai_shang_world_generator/wiki`
