### ISSUE TITLE
use Vercel to deploy dApp

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Web3-dApp-Camp#44]
Money: `¥500`

Deadline: `TBD`

Needs:

- funcs Description
- compare with gh-pages
- using svg-nft as an example

**Comment by Dream4ever** [comment]
I'm coming😄

**Comment by leeduckgo** [comment]
> I'm coming😄 Deadline: 2nd March

Very Wellllllllllll.

**Comment by Dream4ever** [comment]
v1.0: https://m2e7ls709u.feishu.cn/docs/doccnsqNcc7QUqMAn1xyIs3gaEc
