### ISSUE TITLE
【内容产出挑战】Staker

### ISSUE THREAD

**Issue by zhenfeng-zhu** [WeLightProject/Web3-dApp-Camp#99]
实现一个去中心化的Staking dApp。
本文实例亦对应 SpeedrunEthereum（一个 Ethereum 官方的开发者挑战项目）中的Challenge 0x01：
https://speedrunethereum.com/challenge/decentralized-staking

**Comment by zhenfeng-zhu** [comment]
已完成  https://mp.weixin.qq.com/s/HgtPti8pS1J-qpuqI6oUtg

**Comment by leeduckgo** [comment]
Money: `600R`
